In [1]:
import pandas as pd
import numpy as np
from scipy.signal import argrelextrema

df = pd.read_csv("AAPL.csv")

In [2]:
print(df)

         Date        Open        High         Low       Close
0    17-10-17  159.779999  160.869995  159.229996  160.470001
1    18-10-17  160.419998  160.710007  159.600006  159.759995
2    19-10-17  156.750000  157.080002  155.020004  155.979996
3    20-10-17  156.610001  157.750000  155.960007  156.250000
4    23-10-17  156.889999  157.690002  155.500000  156.169998
5    24-10-17  156.289993  157.419998  156.199997  157.100006
6    25-10-17  156.910004  157.550003  155.270004  156.410004
7    26-10-17  157.229996  157.830002  156.779999  157.410004
8    27-10-17  159.289993  163.600006  158.699997  163.050003
9    30-10-17  163.889999  168.070007  163.720001  166.720001
10   31-10-17  167.899994  169.649994  166.940002  169.039993
11   01-11-17  169.869995  169.940002  165.610001  166.889999
12   02-11-17  166.600006  168.500000  165.279999  168.110001
13   03-11-17  174.000000  174.259995  171.119995  172.500000
14   06-11-17  172.369995  174.990005  171.720001  174.250000
15   07-

In [3]:
e = np.array(df['Close'])
print(e)

e.ndim

#import matplotlib.pyplot as plt
#plt.plot(x) # looks good

[160.470001 159.759995 155.979996 156.25     156.169998 157.100006
 156.410004 157.410004 163.050003 166.720001 169.039993 166.889999
 168.110001 172.5      174.25     174.809998 176.240005 175.880005
 174.669998 173.970001 171.339996 169.080002 171.100006 170.149994
 169.979996 173.139999 174.960007 174.970001 174.089996 173.070007
 169.479996 171.850006 171.050003 169.800003 169.639999 169.009995
 169.320007 169.369995 172.669998 171.699997 172.270004 172.220001
 173.970001 176.419998 174.539993 174.350006 175.009995 175.009995
 170.570007 170.600006 171.080002 169.229996 172.259995 172.229996
 173.029999 175.       174.350006 174.330002 174.289993 175.279999
 177.089996 176.190002 179.100006 179.259995 178.460007 177.
 177.039993 174.220001 171.110001 171.509995 167.960007 166.970001
 167.429993 167.779999 160.5      156.490005 163.029999 159.539993
 155.149994 156.410004 162.710007 164.339996 167.369995 172.990005
 172.429993 171.850006 171.070007 172.5      175.5      178.970001
 

1

In [4]:
def get_minmax(e):
    minimum = np.asarray(argrelextrema(e, np.less, order=2))
    maximum = np.asarray(argrelextrema(e, np.greater, order=2))
    return minimum, maximum

In [5]:
c=get_minmax(e)
print(c)

(array([[  2,  21,  24,  30,  35,  45,  48,  51,  58,  71,  75,  78,  86,
         92,  96, 108, 111, 117, 129, 132, 144, 147, 155, 172, 178, 183,
        188, 196, 202, 212, 225, 230, 234, 237, 248]], dtype=int64), array([[ 10,  16,  27,  38,  43,  55,  63,  73,  76,  83,  89,  94,  99,
        109, 116, 124, 141, 145, 152, 159, 163, 177, 181, 189, 193, 201,
        204, 210, 221, 228, 242, 246, 251]], dtype=int64))


In [6]:
e[c[0]], e[c[1]] # access index's values here

(array([[155.979996, 169.080002, 169.979996, 169.479996, 169.009995,
         174.350006, 170.570007, 169.229996, 174.289993, 166.970001,
         156.490005, 155.149994, 171.070007, 175.      , 175.029999,
         164.940002, 166.479996, 168.380005, 162.940002, 162.320007,
         186.440002, 186.309998, 186.869995, 182.169998, 183.919998,
         187.880005, 190.399994, 189.910004, 207.110001, 215.039993,
         218.330002, 217.880005, 217.660004, 220.419998, 214.449997]]),
 array([[169.039993, 176.240005, 174.970001, 172.669998, 176.419998,
         175.      , 179.259995, 167.779999, 163.029999, 172.990005,
         178.970001, 176.820007, 181.720001, 172.770004, 172.800003,
         178.240005, 190.039993, 188.179993, 188.580002, 193.979996,
         192.279999, 187.179993, 190.580002, 191.880005, 194.820007,
         209.070007, 208.880005, 217.580002, 228.360001, 226.410004,
         232.070007, 226.869995, 222.149994]]))

In [15]:
c_merged = np.concatenate(maximum, minimum)
c_merged = np.array(c_merged)
print(c_merged)

TypeError: only integer scalar arrays can be converted to a scalar index

In [25]:
minimum = np.asarray(argrelextrema(e, np.less, order=2))
maximum = np.asarray(argrelextrema(e, np.greater, order=2))

print(minimum)
print(maximum)

print(minimum.type)

#shelf = []
#for value in minimum:
    #minimum[0] += shelf
    

[[  2  21  24  30  35  45  48  51  58  71  75  78  86  92  96 108 111 117
  129 132 144 147 155 172 178 183 188 196 202 212 225 230 234 237 248]]
[[ 10  16  27  38  43  55  63  73  76  83  89  94  99 109 116 124 141 145
  152 159 163 177 181 189 193 201 204 210 221 228 242 246 251]]


AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [ ]:
combined = [] # when they are same length
for i in range(len(minimum)):
    combined.append(maximum(i))
    combined.append(minimum(i))

In [ ]:
# define shape W
# the 2nd leg is 10 - 20% of the first leg

In [ ]:
# Now I need for all these minimas & maximas values:Compare it to next to each other to know how many of them
# satifies the condition of being the range of 4% (but I'm assuming it is 4% of the swing not the value(price)) figure out 
# the swings high -> low & vv.get 20% of the swings to get the pullback and now the 4% is easy peazy  Get the swings done is 
# the next job